# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [ "--maxkb=1024" ]
      - id: check-ast
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: detect-private-key
      - id: no-commit-to-branch
      - id: pretty-format-json
        args: [ '--indent',  '4', '--autofix' ]
  - repo: local
    hooks:
      - id: ruff lint
        name: ruff lint
        entry: ruff check
        args: [ --force-exclude ]
        language: system
        types:
          - python
      - id: ruff format
        name: ruff format
        args: [ --check, --diff, --force-exclude ]
        entry: ruff format
        language: system
        types:
          - python
      - id: mypy
        name: Check typing
        entry: mypy .
        language: system
        types: [ python ]
        pass_filenames: false
